pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/public/' }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

include ':app'

include ':libausbc'
include ':libuvc'
include ':libnative'

project(':libausbc').projectDir = file('AndroidUSBCamera/libausbc')
project(':libuvc').projectDir = file('AndroidUSBCamera/libuvc')
project(':libnative').projectDir = file('AndroidUSBCamera/libnative')